version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    image: webserver:0.0.1
    container_name: webserver
    ports:
    - "8080:80"
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    image: appserver:0.0.1
    container_name: appserver
    ports:
    - "3000:3000"
