version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_web
    image: 170040617115.dkr.ecr.ap-northeast-1.amazonaws.com/webserver:0.0.1
    container_name: webserver
    ports:
    - "80:80"
  appserver:
    build:
      context: .
      dockerfile: Dockerfile_app
    image: 170040617115.dkr.ecr.ap-northeast-1.amazonaws.com/appserver:0.0.1
    container_name: appserver
    ports:
    - "3000:3000"
