FROM nginx:1.15
RUN apt-get update && apt-get install -y --no-install-recommends \
    less \
    curl \
  && :
COPY ./server/webserver/nginx.conf /etc/nginx/nginx.conf
COPY ./dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
